## Installing library

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing library

In [4]:
import numpy

In [21]:
import numpy as np

## Numpy Version Check

In [12]:
np.version.version

'1.19.2'

## 1D Array

In [22]:
first_array = np.array([1,2,3])

In [23]:
first_array

array([1, 2, 3])

## 2D Array

In [24]:
second_array = np.array([(4,5,6),(7,8,9)])

In [25]:
second_array

array([[4, 5, 6],
       [7, 8, 9]])

## 3D array

In [26]:
third_array = np.array([[(10,11,12),(13,14,15)],[(16,17,18),(13,14,15)]])

In [27]:
third_array

array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [13, 14, 15]]])

## Array of zeros

In [28]:
zero_array = np.zeros((3,3))

In [29]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
zero_array = np.ones((5,5))

In [31]:
zero_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
zero_array = np.twoes((2,2))

AttributeError: module 'numpy' has no attribute 'twoes'

## Linspace

numpy.linespace(start,stop,num=)

In [26]:
spaced_numbers = np.linspace(0,20,50)

In [28]:
spaced_numbers

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

## 1D Array

In [55]:
import numpy

In [56]:
import numpy as ss

In [57]:
first_array = ss.array([4,5,6])

In [58]:
first_array

array([4, 5, 6])

## 2D array

In [59]:
second_array = ss.array([(8,3,2),(6,8,9)])

In [60]:
second_array

array([[8, 3, 2],
       [6, 8, 9]])

In [61]:
third_array = ss.array([(75,78,98),(78,90,23)])

In [62]:
third_array

array([[75, 78, 98],
       [78, 90, 23]])

In [63]:
second_array  = ss.ones((2,2))

In [64]:
second_array

array([[1., 1.],
       [1., 1.]])

## Transpose

In [65]:
matrix_transpose = ss.transpose(third_array)

In [66]:
matrix_transpose

array([[75, 78],
       [78, 90],
       [98, 23]])

## Flattening Array

In [67]:
second_array.ravel()

array([1., 1., 1., 1.])

## Reshaping array

In [68]:
first_array.reshape(3,1)

array([[4],
       [5],
       [6]])

## Array Resize

In [69]:
second_array.resize((2,2))

In [70]:
second_array

array([[1., 1.],
       [1., 1.]])

## Appending in array

In [71]:
append_opr = np.append(first_array,second_array)

In [72]:
append_opr

array([4., 5., 6., 1., 1., 1., 1.])

## Inserting array

In [73]:
insert_opr = np.insert(second_array,4,5)

In [74]:
insert_opr

array([1., 1., 1., 1., 5.])

In [78]:
insert2 = np.insert(second_array,3,10)

In [79]:
insert2

array([ 1.,  1.,  1., 10.,  1.])

## deleting array

In [80]:
np.delete(insert2,[4])

array([ 1.,  1.,  1., 10.])

In [81]:
ss.delete(insert2,[0,1])

array([ 1., 10.,  1.])

## Subsetting array

In [82]:
insert_opr

array([ 1.,  1.,  1., 10.,  1.])

In [85]:
second_array

array([[1., 1.],
       [1., 1.]])

In [86]:
insert_opr[3]

10.0

In [88]:
second_array[0,1]

1.0

## Slicing in array

In [90]:
insert2

array([ 1.,  1.,  1., 10.,  1.])

In [95]:
insert2[0:2]

array([1., 1.])

In [96]:
insert2[2:]

array([ 1., 10.,  1.])

In [97]:
second_array

array([[1., 1.],
       [1., 1.]])

In [98]:
second_array[:1]

array([[1., 1.]])

## Creating empty array

In [100]:
ss.empty((2,2))

array([[1., 1.],
       [1., 1.]])

## Array with Random numbers

In [101]:
ss.random.random((3,4))

array([[0.25445141, 0.81697639, 0.4709458 , 0.90195521],
       [0.1878986 , 0.70874502, 0.46248799, 0.72466281],
       [0.82824357, 0.89485749, 0.26837181, 0.84971037]])